# High-Risk 15-Minute CipherB Trading System Configuration
# Market Cap >= 100M, Volume >= 20M, 15-Minute Timeframe Analysis

# High-Risk 15-Minute CipherB Trading System Configuration
# Market Cap >= 100M, Volume >= 20M, 15-Minute Timeframe Analysis

system:
  name: "CipherB Professional 15m"
  version: "1.0"
  timeframe: "15m"
  timezone: "Asia/Kolkata"

apis:
  coingecko:
    base_url: "https://api.coingecko.com/api/v3"
    rate_limit: 1.5
    timeout: 30

exchange:
  primary: "bingx"
  fallback:
    - "kucoin"
    - "bybit"
  rate_limit_sec: 0.3
  timeout_sec: 20

filters:
  min_market_cap: 100000000
  min_volume_24h: 20000000

alert:
  max_coins_per_run: 165
  cooldown_minutes: 15
  batch_size: 25

scan:
  pages: 3
  coins_per_page: 150
  candles_required: 200

cipherb:
  wt_channel_len: 9
  wt_average_len: 12
  wt_ma_len: 3
  oversold_threshold: -60
  overbought_threshold: 60
