system:
  name: "Professional 15m CipherB System"
  version: "1.0"
  timeframe: "15m"
  timezone: "Asia/Kolkata"

apis:
  coingecko:
    base_url: "https://api.coingecko.com/api/v3"
    rate_limit: 2.0
    timeout: 60

exchange:
  primary: "bingx"
  fallback: ["kucoin", "bybit"]
  rate_limit_sec: 0.5
  timeout_sec: 30

filters:
  min_market_cap: 100000000
  min_volume_24h: 20000000

# Pure CipherB settings (same as your working 2h system)
cipherb:
  wt_channel_len: 9
  wt_average_len: 12
  wt_ma_len: 3
  oversold_threshold: -60
  overbought_threshold: 60

scan:
  pages: 3
  coins_per_page: 125
  candles_required: 200
