# High-Risk 15-Minute CipherB Trading System Configuration
# Market Cap >= 100M, Volume >= 20M, 15-Minute Timeframe Analysis

system:
  name: "CipherB Professional 15m"
  version: "1.0"
  timeframe: "15m"
  timezone: "Asia/Kolkata"

apis:
  coingecko:
    base_url: "https://api.coingecko.com/api/v3"
    rate_limit: 4.0  # 4 seconds between requests (safer)
    timeout: 60      # 60 seconds timeout

exchange:
  primary: "bingx"
  fallback: ["kucoin", "bybit"]
  rate_limit_sec: 0.5
  timeout_sec: 30

filters:
  min_market_cap: 100000000    # 100M (reduced for more coins)
  min_volume_24h: 20000000    # 20M (reduced for more coins)

alert:
  max_coins_per_run: 200
  cooldown_minutes: 15
  batch_size: 20

scan:
  pages: 2          # Reduced to avoid timeouts
  coins_per_page: 100  # Reduced for reliability
  candles_required: 200

cipherb:
  wt_channel_len: 9
  wt_average_len: 12
  wt_ma_len: 3
  oversold_threshold: -60
  overbought_threshold: 60
