# High-Risk 15-Minute CipherB Trading System Configuration
# Market Cap >= 100M, Volume >= 20M, 15-Minute Timeframe Analysis

# High-Risk 15-Minute CipherB Trading System Configuration
# Market Cap >= 100M, Volume >= 20M, 15-Minute Timeframe Analysis

system:
  name: "CipherB High-Risk 15m System"
  version: "1.0"
  timeframe: "15m"
  timezone: "+05:30"  # IST

# API Configuration
coingecko:
  base_url: "https://api.coingecko.com/api/v3"
  rate_limit: 1.5
  timeout: 30

exchanges:
  primary: "bingx"
  fallback: ["kucoin", "bybit"]
  rate_limit: 0.2
  timeout: 25
  
# High-Risk Market Filter (165 Quality Coins)
market_filter:
  min_market_cap: 100000000   # 100M USD
  min_volume_24h: 20000000    # 20M USD
  description: "High-volatility coins with established liquidity"

# CipherB Indicator Settings (15-Minute Optimized)
cipherb:
  timeframe: "15m"
  wt_channel_len: 9
  wt_average_len: 12
  wt_ma_len: 3
  oversold_threshold: -60
  overbought_threshold: 60
  heikin_ashi: true

# High-Risk Alert System
alerts:
  cooldown_candles: 1  # One alert per 15m candle
  max_coins_per_run: 165
  batch_size: 25
  enable_high_risk_mode: true
  telegram_chat_id_env: "HIGH_RISK_TELEGRAM_CHAT_ID"

# Scanning Configuration (15m Optimized)
scan:
  pages: 4
  coins_per_page: 250
  candles_required: 200  # 15m candles for analysis
