# High-Risk 15-Minute CipherB Trading System Configuration
# Market Cap >= 100M, Volume >= 20M, 15-Minute Timeframe Analysis

system:
  name: "CipherB Professional 15m"
  version: "1.0"
  timeframe: "15m"
  timezone: "Asia/Kolkata"

apis:
  coingecko:
    base_url: "https://api.coingecko.com/api/v3"
    rate_limit: 3.0  # Increased delay between requests
    timeout: 60      # Increased timeout to 60 seconds

exchange:
  primary: "bingx"
  fallback:
    - "kucoin" 
    - "bybit"
  rate_limit_sec: 0.5  # Slightly slower to avoid issues
  timeout_sec: 30

filters:
  min_market_cap: 50000000    # Reduced to 50M to get more coins
  min_volume_24h: 10000000    # Reduced to 10M to get more coins

alert:
  max_coins_per_run: 165
  cooldown_minutes: 15
  batch_size: 20  # Smaller batches for stability

scan:
  pages: 2          # Reduced pages to avoid timeouts  
  coins_per_page: 100  # Smaller page size for reliability
  candles_required: 200

cipherb:
  wt_channel_len: 9
  wt_average_len: 12
  wt_ma_len: 3
  oversold_threshold: -60
  overbought_threshold: 60
