# High-Risk 15-Minute CipherB Trading System Configuration
# Market Cap >= 100M, Volume >= 20M, 15-Minute Timeframe Analysis

system:
  name: "CipherB High-Risk 15m System"
  version: "2.0"
  timeframe: "15m"
  timezone: "+05:30"

market_filter:
  min_market_cap: 100000000
  min_volume_24h: 20000000

cipherb:
  wt_channel_len: 9
  wt_average_len: 12
  wt_ma_len: 3
  oversold_threshold: -60
  overbought_threshold: 60

vwma:
  period: 21

alerts:
  monitor_chat_env: "TELEGRAM_MONITOR_CHAT_ID"
  execute_chat_env: "TELEGRAM_EXECUTE_CHAT_ID"
  cooldown_candles: 1
  max_coins_per_run: 165
  batch_size: 25

scan:
  pages: 4
  coins_per_page: 250
  candles_required: 200
